/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */
package edu.iu.finch.core;

public enum NexRadStation {
    FOP1("FOP1"),
    KABR("KABR"),
    KABX("KABX"),
    KAKQ("KAKQ"),
    KAMA("KAMA"),
    KAMX("KAMX"),
    KAPX("KAPX"),
    KARX("KARX"),
    KATX("KATX"),
    KBBX("KBBX"),
    KBGM("KBGM"),
    KBHX("KBHX"),
    KBIS("KBIS"),
    KBLX("KBLX"),
    KBMX("KBMX"),
    KBOX("KBOX"),
    KBRO("KBRO"),
    KBUF("KBUF"),
    KBYX("KBYX"),
    KCAE("KCAE"),
    KCBW("KCBW"),
    KCBX("KCBX"),
    KCCX("KCCX"),
    KCLE("KCLE"),
    KCLX("KCLX"),
    KCRP("KCRP"),
    KCXX("KCXX"),
    KCYS("KCYS"),
    KDAX("KDAX"),
    KDDC("KDDC"),
    KDFX("KDFX"),
    KDGX("KDGX"),
    KDIX("KDIX"),
    KDLH("KDLH"),
    KDMX("KDMX"),
    KDOX("KDOX"),
    KDTX("KDTX"),
    KDVN("KDVN"),
    KDYX("KDYX"),
    KEAX("KEAX"),
    KEMX("KEMX"),
    KENX("KENX"),
    KEOX("KEOX"),
    KEPZ("KEPZ"),
    KESX("KESX"),
    KEVX("KEVX"),
    KEWX("KEWX"),
    KEYX("KEYX"),
    KFCX("KFCX"),
    KFDR("KFDR"),
    KFDX("KFDX"),
    KFFC("KFFC"),
    KFSD("KFSD"),
    KFSX("KFSX"),
    KFTG("KFTG"),
    KFWS("KFWS"),
    KGGW("KGGW"),
    KGJX("KGJX"),
    KGLD("KGLD"),
    KGRB("KGRB"),
    KGRK("KGRK"),
    KGRR("KGRR"),
    KGSP("KGSP"),
    KGWX("KGWX"),
    KGYX("KGYX"),
    KHDX("KHDX"),
    KHGX("KHGX"),
    KHNX("KHNX"),
    KHPX("KHPX"),
    KHTX("KHTX"),
    KICT("KICT"),
    KICX("KICX"),
    KILN("KILN"),
    KILX("KILX"),
    KIND("KIND"),
    KINX("KINX"),
    KIWA("KIWA"),
    KIWX("KIWX"),
    KJAX("KJAX"),
    KJGX("KJGX"),
    KJKL("KJKL"),
    KLBB("KLBB"),
    KLCH("KLCH"),
    KLGX("KLGX"),
    KLIX("KLIX"),
    KLNX("KLNX"),
    KLOT("KLOT"),
    KLRX("KLRX"),
    KLSX("KLSX"),
    KLTX("KLTX"),
    KLVX("KLVX"),
    KLWX("KLWX"),
    KLZK("KLZK"),
    KMAF("KMAF"),
    KMAX("KMAX"),
    KMBX("KMBX"),
    KMHX("KMHX"),
    KMKX("KMKX"),
    KMLB("KMLB"),
    KMOB("KMOB"),
    KMPX("KMPX"),
    KMQT("KMQT"),
    KMRX("KMRX"),
    KMSX("KMSX"),
    KMTX("KMTX"),
    KMUX("KMUX"),
    KMVX("KMVX"),
    KMXX("KMXX"),
    KNKX("KNKX"),
    KNQA("KNQA"),
    KOAX("KOAX"),
    KOHX("KOHX"),
    KOKX("KOKX"),
    KOTX("KOTX"),
    KPAH("KPAH"),
    KPBZ("KPBZ"),
    KPDT("KPDT"),
    KPOE("KPOE"),
    KPUX("KPUX"),
    KRAX("KRAX"),
    KRGX("KRGX"),
    KRIW("KRIW"),
    KRLX("KRLX"),
    KRTX("KRTX"),
    KSFX("KSFX"),
    KSGF("KSGF"),
    KSHV("KSHV"),
    KSJT("KSJT"),
    KSOX("KSOX"),
    KSRX("KSRX"),
    KTBW("KTBW"),
    KTFX("KTFX"),
    KTLH("KTLH"),
    KTLX("KTLX"),
    KTWX("KTWX"),
    KTYX("KTYX"),
    KUDX("KUDX"),
    KUEX("KUEX"),
    KVAX("KVAX"),
    KVBX("KVBX"),
    KVNX("KVNX"),
    KVTX("KVTX"),
    KVWX("KVWX"),
    KYUX("KYUX"),
    PABC("PABC"),
    PACG("PACG"),
    PAEC("PAEC"),
    PAHG("PAHG"),
    PAIH("PAIH"),
    PAKC("PAKC"),
    PAPD("PAPD"),
    PGUA("PGUA"),
    PHKI("PHKI"),
    PHKM("PHKM"),
    PHMO("PHMO"),
    PHWA("PHWA"),
    RKJK("RKJK"),
    RKSG("RKSG"),
    TJUA("TJUA");

    private String  name;
    NexRadStation(String _name){
        this.name = _name;
    }


    @Override
    public String toString() {
        return name;
    }
}
